# Generated by Django 2.1 on 2018-09-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='Likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='Views',
            new_name='views',
        ),
        migrations.AddField(
            model_name='place',
            name='creater',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mainImage'),
        ),
    ]
